// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: demo/demo.proto

package lb_algo_dispatcher

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AlgoDispatcher service

type AlgoDispatcherService interface {
	// Demo
	GetDemo(ctx context.Context, in *DemoRequest, opts ...client.CallOption) (*DemoListReply, error)
}

type algoDispatcherService struct {
	c    client.Client
	name string
}

func NewAlgoDispatcherService(name string, c client.Client) AlgoDispatcherService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "lb.algo.dispatcher"
	}
	return &algoDispatcherService{
		c:    c,
		name: name,
	}
}

func (c *algoDispatcherService) GetDemo(ctx context.Context, in *DemoRequest, opts ...client.CallOption) (*DemoListReply, error) {
	req := c.c.NewRequest(c.name, "AlgoDispatcher.GetDemo", in)
	out := new(DemoListReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AlgoDispatcher service

type AlgoDispatcherHandler interface {
	// Demo
	GetDemo(context.Context, *DemoRequest, *DemoListReply) error
}

func RegisterAlgoDispatcherHandler(s server.Server, hdlr AlgoDispatcherHandler, opts ...server.HandlerOption) error {
	type algoDispatcher interface {
		GetDemo(ctx context.Context, in *DemoRequest, out *DemoListReply) error
	}
	type AlgoDispatcher struct {
		algoDispatcher
	}
	h := &algoDispatcherHandler{hdlr}
	return s.Handle(s.NewHandler(&AlgoDispatcher{h}, opts...))
}

type algoDispatcherHandler struct {
	AlgoDispatcherHandler
}

func (h *algoDispatcherHandler) GetDemo(ctx context.Context, in *DemoRequest, out *DemoListReply) error {
	return h.AlgoDispatcherHandler.GetDemo(ctx, in, out)
}
